### ISSUE TITLE
MATLAB style guidelines and automatic documentation

### ISSUE THREAD

**Issue by kshitijgoel007** [kshitijgoel007/AUVForwardDynamics#8]
The repository has to follow MATLAB style guidelines as mentioned [here](http://www.datatool.com/downloads/matlab_style_guidelines.pdf). Automatic documentation capability is really cool in MATLAB and we should get it generated quickly.

This can be open for KWoC.

attn : @shubhamjena @AlphaMale1996

**Comment by shubhamjena** [comment]
the link is not opening

**Comment by kshitijgoel007** [comment]
Fixed https://github.com/kshitijgoel007/AUVForwardDynamics/commit/32aa9ed8de2902e0217247ad0c2d03511aeea6dc
